/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lcy_aspire_utils_JniUtils */

#ifndef _Included_com_lcy_aspire_utils_JniUtils
#define _Included_com_lcy_aspire_utils_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lcy_aspire_utils_JniUtils
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lcy_aspire_utils_JniUtils_getCLanguageString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
